#!/usr/bin/env python3
"""Assign the nine real trainees to the placeholder rows and redistribute the
season's pairs. Deterministic (seeded), so re-running gives the same answer.

Writes:
  migrations/2026-09-assign-trainees.sql   — run in the Supabase SQL Editor
  Mishmer-section/2026-27/schedule.md      — the owners column
  Mishmer-section/2026-27/students.md      — the per-trainee table
  students_tasks.md                        — the «אחראים» lines (the first-run seed)

Rules (asserted below): #01–#02 stay צוות; 19 Mishmarim × 2 = 38 slots over 9
trainees → seven get 4, two get 5; two different trainees per Mishmar; no
trainee on two consecutive Mishmarim; all 19 pairs distinct; the tenth
placeholder row is deleted.
"""
import random, re, sys
from pathlib import Path

NAMES = ["איתי בן מנחם", "איתי בן יהודה", "אלה מאיר", "זואה כהן", "יותם ספיר",
         "יעל שם טוב", "כליל בלאוקופף", "רוני פרנקל", "רותם דרור"]
STAFF = (1, 2)
MISHMARIM = list(range(3, 22))          # #03–#21
SEED = 5787
ROOT = Path(__file__).resolve().parent.parent


def draw(rng: random.Random):
    """One attempt: fill the slots round by round and check the rules."""
    ids = list(range(1, 10))
    quota = {i: 4 for i in ids}
    for i in rng.sample(ids, 2):
        quota[i] = 5
    pairs, used_pairs, prev = {}, set(), set()
    for mid in MISHMARIM:
        pool = [i for i in ids if quota[i] > 0 and i not in prev]
        rng.shuffle(pool)
        # prefer the trainees with the most remaining quota, ties broken by the shuffle
        pool.sort(key=lambda i: -quota[i])
        chosen = None
        for a in range(len(pool)):
            for b in range(a + 1, len(pool)):
                pr = tuple(sorted((pool[a], pool[b])))
                if pr not in used_pairs:
                    chosen = pr
                    break
            if chosen:
                break
        if not chosen:
            return None
        used_pairs.add(chosen)
        pairs[mid] = chosen
        for i in chosen:
            quota[i] -= 1
        prev = set(chosen)
    if any(q != 0 for q in quota.values()):
        return None
    return pairs


def main():
    rng = random.Random(SEED)
    names = NAMES[:]
    rng.shuffle(names)                      # name → student id 1..9, at random
    by_id = {i + 1: n for i, n in enumerate(names)}
    pairs = None
    for _ in range(10000):
        pairs = draw(rng)
        if pairs:
            break
    assert pairs, "no assignment satisfied the rules"
    # ---- assertions: the rules, checked, not assumed ----
    load = {i: 0 for i in by_id}
    prev = ()
    seen = set()
    for mid in MISHMARIM:
        a, b = pairs[mid]
        assert a != b and not ({a, b} & set(prev)), f"consecutive at #{mid}"
        assert (a, b) not in seen, f"pair repeats at #{mid}"
        seen.add((a, b)); prev = (a, b)
        load[a] += 1; load[b] += 1
    assert sorted(load.values()) == [4] * 7 + [5] * 2, load
    # ---- SQL ----
    sql = ["-- Nine trainees onto the placeholder rows, and the season's pairs redistributed.",
           "-- Generated by scripts/assign_trainees.py (seed %d). Idempotent: run as often as needed." % SEED,
           "BEGIN;"]
    for i, n in by_id.items():
        sql.append(f"UPDATE students SET name = '{n}' WHERE id = {i};")
    sql.append("DELETE FROM students WHERE id = 10;   -- assignments cascade; other student_id refs go NULL")
    sql.append(f"DELETE FROM assignments WHERE mishmar_id BETWEEN {MISHMARIM[0]} AND {MISHMARIM[-1]};")
    for mid in MISHMARIM:
        for i in pairs[mid]:
            sql.append(f"INSERT INTO assignments (mishmar_id, student_id) VALUES ({mid}, {i}) ON CONFLICT DO NOTHING;")
    sql.append("COMMIT;")
    (ROOT / "migrations").mkdir(exist_ok=True)
    (ROOT / "migrations/2026-09-assign-trainees.sql").write_text("\n".join(sql) + "\n", encoding="utf-8")

    def owners(mid):
        a, b = pairs[mid]
        return f"{by_id[a]} + {by_id[b]}"
    # ---- schedule.md: the owners column of #03–#21 ----
    sched = ROOT / "Mishmer-section/2026-27/schedule.md"
    txt = sched.read_text(encoding="utf-8")
    def fix_row(m):
        mid = int(m.group(1))
        return m.group(0) if mid in STAFF else m.group(0).replace(m.group(2), owners(mid), 1)
    txt = re.sub(r"^\| (\d\d) \|[^\n]*?\| ((?:חניך \d+ \+ חניך \d+)|(?:[^|]+ \+ [^|]+?)) \|", fix_row, txt, flags=re.M)
    txt = txt.replace("שאר האחראים מסומנים בשמות placeholder (**חניך 1**–**חניך 10**) עד שיגיעו השמות האמיתיים — ראו \"שיבוץ החניכים\".",
                      "האחראים הם תשעת החניכים של השנה — השיבוץ נוצר על ידי `scripts/assign_trainees.py` ומוחל במסד דרך `migrations/2026-09-assign-trainees.sql`.")
    sched.write_text(txt, encoding="utf-8")
    # ---- students_tasks.md: the seed's owners lines AND its index table ----
    # The first-run seed builds the student list from the index table's first
    # column and the assignments from the «אחראים» lines; both must carry the
    # real names, or a fresh database gets placeholders and no pairs.
    seed = ROOT / "students_tasks.md"
    t = seed.read_text(encoding="utf-8")
    cur = None
    out = []
    in_index = False
    index_done = False
    for line in t.splitlines(keepends=True):
        m = re.match(r"### משמר #(\d\d) ", line)
        if m:
            cur = int(m.group(1))
        if cur is None and line.startswith("| חניך") and not index_done and not in_index:
            # header row of the index table: emit the header + the nine rows
            in_index = True
            out.append("| חניך/ה | משמרים | סה״כ |\n|---|---|---|\n")
            for i, n in by_id.items():
                mine = [mid for mid in MISHMARIM if i in pairs[mid]]
                cells = " · ".join(f"[#{mid:02d}](#משמר-{mid:02d})" for mid in mine)
                out.append(f"| {n} | {cells} | {len(mine)} |\n")
            continue
        if in_index:
            if line.startswith("|") and "**צוות**" not in line:
                continue              # the old header separator / placeholder rows
            if "**צוות**" in line:
                out.append(line)
                in_index = False
                index_done = True
                continue
        if cur is None and line.startswith("> **שמות:**"):
            line = ("> **שמות:** תשעת החניכים של השנה — השיבוץ נוצר על ידי "
                    "`scripts/assign_trainees.py` ומוחל במסד דרך "
                    "`migrations/2026-09-assign-trainees.sql`; הזריעה הראשונה קוראת "
                    "את השמות מהטבלה שלמטה.\n")
        if cur and cur not in STAFF and "**אחראים:**" in line:
            line = re.sub(r"\*\*אחראים:\*\* (?:חניך \d+|[^+·]+?) \+ (?:חניך \d+|[^·\n]+?)(?= ·|\n)",
                          f"**אחראים:** {owners(cur)}", line)
        out.append(line)
    seed.write_text("".join(out), encoding="utf-8")
    # ---- students.md: rewritten table ----
    rows = []
    for i, n in by_id.items():
        mine = [f"{mid:02d}" for mid in MISHMARIM if i in pairs[mid]]
        gaps = [MISHMARIM.index(int(b)) - MISHMARIM.index(int(a)) for a, b in zip(mine, mine[1:])]
        rows.append(f"| {n} | {', '.join(mine)} | {len(mine)} | {min(gaps)} שבועות |")
    students = ROOT / "Mishmer-section/2026-27/students.md"
    students.write_text(
        "# חניכים — תשפ״ז / 2026-27\n\n"
        "> תשעה חניכים. השיבוץ מכסה **משמרים #03–21 בלבד** — #01 (משמר בוגרים) ו-#02 נבנים על ידי הצוות.\n"
        "> נוצר על ידי `scripts/assign_trainees.py` (זרע קבוע, ולכן ניתן לשחזור), ומוחל במסד דרך\n"
        "> `migrations/2026-09-assign-trainees.sql`. המסד הוא האמת; הקבצים כאן מתעדים אותו.\n\n"
        "## השיבוץ\n\nסך הכל 38 שיבוצים (19 משמרים × 2) על 9 חניכים: שבעה עם 4 משמרים ושניים עם 5.\n\n"
        "| חניך/ה | משמרים | סה״כ | מרווח מינימלי |\n|---|---|---|---|\n" + "\n".join(rows) + "\n\n"
        "## כללי השיבוץ\n\n1. **שני אחראים לכל משמר** — לא ל-#01–02.\n"
        "2. **עומס מאוזן** — 38 שיבוצים על 9 = 4.2 בממוצע; 7×4 + 2×5.\n"
        "3. **בלי זוגות חוזרים** — 19 הזוגות שונים זה מזה (מתוך 36 האפשריים).\n"
        "4. **בלי משמרים רצופים לאותו חניך** — מרווח של שבוע לפחות בין שני משמרים של אותו אדם.\n",
        encoding="utf-8")
    print("student ids:", by_id)
    for mid in MISHMARIM:
        print(f"  #{mid:02d}: {owners(mid)}")
    print("load:", {by_id[i]: v for i, v in load.items()})
    print("wrote migrations/2026-09-assign-trainees.sql, schedule.md, students.md, students_tasks.md")


if __name__ == "__main__":
    main()
