#!/usr/bin/env python3
"""Generate .claude/rules/streamlit-dom.md from the INSTALLED Streamlit bundle.

Why: the rules once described a testid (stVerticalBlockBorderWrapper) that the
bundle no longer had, and the card primitive was silently unstyled for a whole
release. This file is the ground truth Claude reads before touching RTL_CSS —
regenerate it after every Streamlit upgrade. stdlib only.
Usage: python3 scripts/streamlit_dom_context.py [--check]   (--check: exit 1 if stale)
"""
import glob, os, re, sys
import streamlit

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   ".claude", "rules", "streamlit-dom.md")
JS = os.path.join(os.path.dirname(streamlit.__file__), "static", "static", "js")
bundle = "".join(open(f, errors="ignore").read() for f in glob.glob(os.path.join(JS, "*.js")))
# the bundle emits `"data-testid":\`stButton\`` (template literal), `data-testid="st…"`
# and `data-testid:"st…"` — catch all three, and only values that start with st+Capital
ids = sorted(set(re.findall(r'data-testid["\']?\s*[:=]\s*[`"\']?(st[A-Z][A-Za-z0-9]+)', bundle)))
ids = [i for i in ids if len(i) < 48]

# facts that only a live DOM tells you — measured, dated by version
FACTS = """
## Structural facts (measured in headless Chromium, Streamlit {v})

- `st.container(border=True)`: the border, radius and padding sit on the **`stVerticalBlock`
  itself** (emotion hash `xaibe2` in 1.62.0; unchanged through 1.64.0); it also carries `data-test-scroll-behavior`, but
  so do width-only, keyed and fragment wrappers (hash `1n6tfoc`) — that attribute is NOT a card
  selector. The app styles cards opt-in through their key (`.st-key-card-…`). The old `…BlockBorderWrapper` testid no longer exists.
- **`st.dialog`, popovers, toasts and the select dropdown are portaled to `<body>`** — OUTSIDE
  `stAppViewContainer`, so nothing scoped to that container reaches them (measured: a dialog's
  `parentElement` is `BODY` and its computed direction was `ltr` under an RTL app). The app names
  `stDialog` / `stPopoverBody` / `stToastContainer` / `stSelectboxVirtualDropdown` explicitly.
- **The selectbox is react-aria, not BaseWeb**: `[data-baseweb="select"]` matches zero nodes; the
  control is `[data-testid="stSelectbox"] div[role="group"]`, the value lives in its `input`.
- **`stMarkdownContainer` carries `margin-bottom: -16px`** (it cancels a trailing `<p>`'s margin).
  A raw-HTML block ending in a `<div>` loses 16px of real height and the next element draws over it.
- `st.container(width=N)` / `st.container(horizontal=True)`: the sizing is on a
  **`stLayoutWrapper`** around the block (`flex: 0 0 fit-content` for `width="content"`).
- `st.columns` → `stLayoutWrapper > stHorizontalBlock > stColumn`.
- `st.caption` → `stCaptionContainer` (NOT `stMarkdownContainer`); `st.feedback` →
  `stFeedback` / `stFeedbackButton`; `st.segmented_control` and `st.pills` → `stButtonGroup`
  (labels via DynamicButtonLabel, not markdown — need their own RTL rule).
- Material icons are ligature text: a `<span translate="no">` whose text is the icon NAME. The
  bundle sets `translate: no` in exactly two places, both icon components, and only some carry
  `stIconMaterial` — the status widget's tick is `stExpanderIconCheck`. A font override that
  reaches them paints the literal word (measured on 1.64: «check» clipped to «chec» beside
  «הסריקה הסתיימה»). Carve out `[data-testid="stIconMaterial"], [data-testid^="stExpanderIcon"],
  span[translate="no"]`.
- **The radio's DOM moved in 1.64** (measured against the 1.63 and 1.64 bundles): 1.63 is
  `div[stRadioGroup][role=radiogroup] > label[stRadioOption] > span(input) + div > div(row) >
  div(circle)`; 1.64 inserts a react-aria wrapper — `div[stRadioGroup] > div > label[stRadioOption]
  > span(input) + div(row) > div(circle)` — so every `radiogroup > label` rule went dead, and the
  circle sits one level higher. Anchors that hold in both: `label[data-testid="stRadioOption"]`,
  `[data-testid="stRadioGroup"] > *`, react-aria's `data-selected` / `data-focus-visible` on the
  label, the circle's emotion target class per version (`eqiohyi4` 1.62/63, `e1mpz0hj4` 1.64) and
  the structural `div:has(> div:only-child:empty)`. A role selector (`div[role=…]`) is a blind spot
  for a testid-only audit — the same class of miss as `data-baseweb`.
- The sidebar collapse is a `transform: translateX(-width)` in the bundle — wrong under RTL;
  `RTL_CSS` neutralises it.
- Keyed containers → class `st-key-<key>` on the `stVerticalBlock` / `stHorizontalBlock` itself.
"""

body = (f"---\npaths:\n  - app.py\n  - chat_panel.py\n---\n\n"
        f"# Streamlit DOM context — generated, do not edit by hand\n\n"
        f"Generated by `scripts/streamlit_dom_context.py` from the installed bundle of "
        f"**Streamlit {streamlit.__version__}**. A `data-testid` used in `RTL_CSS` that is not in "
        f"this list is a dead rule. Regenerate after every Streamlit upgrade; `design-review` "
        f"and `app-reviewer` read this instead of remembering.\n\n"
        f"## `data-testid` values present in the bundle ({len(ids)})\n\n"
        + " · ".join(f"`{i}`" for i in ids) + "\n" + FACTS.format(v=streamlit.__version__))

if "--check" in sys.argv:
    cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    sys.exit(0 if cur == body else 1)
open(OUT, "w", encoding="utf-8").write(body)
print(f"wrote {OUT}: {len(ids)} testids, Streamlit {streamlit.__version__}")
